# Generated by Django 6.0.4 on 2026-04-14 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('operador', 'Operador'), ('consultor', 'Consultor')], default='operador', max_length=10),
        ),
    ]
